const cardsData = {
  'c26j-SSR-ikki':               { name: 'イッキ',              rarity: 'SSR', oura: '黄', type: '友人',       mon: null,   ext: 'jpg' },
  'c25j-SSR-metabee':           { name: 'メタビー',            rarity: 'SSR', oura: '黄', type: '丈夫さ',     mon: '無機', ext: 'jpg' },
  'c24j-MR-ikki':               { name: 'イッキ',              rarity: 'MR',  oura: '黄', type: '友人',       mon: null,   ext: 'jpg' },
  'a13i-MR-nishiki':          { name: 'ニシキ',              rarity: 'MR',  oura: '赤', type: 'テクニック', mon: '魔族', ext: 'jpg', event2: '超逆上' },
  'b16i-MR-diana':          { name: 'ディアナ',          rarity: 'MR',  oura: '青', type: 'インパクト', mon: '魔族', ext: 'jpg', dist: '遠距離' },
  'b5g-SSR-norun':          { name: 'ノルン',            rarity: 'SSR', oura: '青', type: '回避',       mon: '創造', ext: 'jpg' },
  'f18l-MR-esueru':           { name: 'エスエル',          rarity: 'MR',  oura: '黒', type: 'フォース',   mon: '無機', ext: 'jpg', event2: '超闘魂' },
  'a10j-SSR-fureria':         { name: 'フレリア',          rarity: 'SSR', oura: '赤', type: '師匠',       mon: '獣',   ext: 'jpg' },
  'a4g-SSR-karukinosu':       { name: 'カルキノス',        rarity: 'SSR', oura: '赤', type: '命中',       mon: '創造', ext: 'jpg', event2: '超闘魂' },
  'a24j-MR-vitoniru':         { name: 'ヴィトニル',        rarity: 'MR',  oura: '赤', type: 'メンタル',   mon: '獣',   ext: 'jpg', dist: '中距離' },
  'a10j-MR-fureria':          { name: 'フレリア',          rarity: 'MR',  oura: '赤', type: '師匠',       mon: '獣',   ext: 'jpg' },
  'f14g-MR-darasu':           { name: 'ダラス',            rarity: 'MR',  oura: '黒', type: 'フィジカル', mon: '創造', ext: 'jpg', dist: '近距離' },
  'f2k-SSR-shionresort':      { name: 'シオン・リゾート',  rarity: 'SSR', oura: '黒', type: 'ちから',     mon: '怪物', ext: 'jpg', terrain: '海岸' },
  'a6i-SSR-mirimuresort':     { name: 'ミリム・リゾート',  rarity: 'SSR', oura: '赤', type: '丈夫さ',     mon: '魔族', ext: 'jpg', event2: '超本気' },
  'b5i-SSR-rimurugurasan':    { name: 'リムル・グラサン',  rarity: 'SSR', oura: '青', type: '回避',       mon: '魔族', ext: 'jpg', dist: '零距離' },
  'a7-MR-syuna':              { name: 'シュナ',            rarity: 'MR',  oura: '赤', type: '友人',       mon: null,   ext: 'jpg' },
  'b21i-MR-rimuru':           { name: 'リムル・リゾート',  rarity: 'MR',  oura: '青', type: 'クイック',   mon: '魔族', ext: 'jpg', dist: '零距離' },
  'f24i-MR-megaranika':       { name: 'メガラニカ',        rarity: 'MR',  oura: '黒', type: 'メンタル',   mon: '魔族', ext: 'jpg', event2: '超憤怒' },
  'e7-MR-sutera':             { name: 'ステラ',            rarity: 'MR',  oura: '白', type: '友人',       mon: null,   ext: 'jpg' },
  'e20i-MR-nadeshiko':        { name: 'ナデシコ',          rarity: 'MR',  oura: '白', type: 'サバイブ',   mon: '魔族', ext: 'jpg', dist: '近距離' },
  'c12l-MR-gifton':           { name: 'ギフトン',          rarity: 'MR',  oura: '黄', type: 'アサルト',   mon: '無機', ext: 'jpg', terrain: '雪山' },
  'c19h-MR-aufieru':          { name: 'アウフィエル',      rarity: 'MR',  oura: '黄', type: 'ジャッジ',   mon: '幻霊', ext: 'jpg', event2: '超余裕' },
  'c9-SSR-safin':             { name: 'サフィン',          rarity: 'SSR', oura: '黄', type: 'ライバル',   mon: null,   ext: 'jpg' },
  'f5l-SSR-sharutia':         { name: 'シャルティア',      rarity: 'SSR', oura: '赤', type: '回避',       mon: '無機', ext: 'jpg', dist: '遠距離' },
  'f7-MR-demiurugosu':        { name: 'デミウルゴス',      rarity: 'MR',  oura: '黒', type: '友人',       mon: null,   ext: 'jpg' },
  'f18k-MR-ainzu':            { name: 'アインズ',          rarity: 'MR',  oura: '黒', type: 'フォース',   mon: '怪物', ext: 'jpg', event2: '超本気' },
  'd14k-MR-sukeakurou':       { name: 'スケアクロウ',      rarity: 'MR',  oura: '緑', type: 'フィジカル', mon: '怪物', ext: 'jpg', terrain: '砂漠' },
  'd9-SSR-airisu':            { name: 'アイリス(ライバル)', rarity: 'SSR', oura: '緑', type: 'ライバル',  mon: null,   ext: 'jpg' },
  'b7-MR-kurisu':             { name: 'クリス',            rarity: 'MR',  oura: '青', type: '友人',       mon: null,   ext: 'jpg' },
  'd18k-MR-furan':            { name: 'フラン',            rarity: 'MR',  oura: '緑', type: 'フォース',   mon: '怪物', ext: 'jpg', event2: '超根性' },
  'b2h-SSR-sappirutti':       { name: 'サフィルス',        rarity: 'SSR', oura: '青', type: 'ちから',     mon: '幻霊', ext: 'jpg', terrain: '海岸' },
  'b22h-MR-noa':              { name: 'ノア',              rarity: 'MR',  oura: '青', type: 'ルミナス',   mon: '幻霊', ext: 'jpg', dist: '近距離' },
  'f3k-SSR-baromu':           { name: 'バロム',            rarity: 'SSR', oura: '黒', type: 'かしこさ',   mon: '怪物', ext: 'jpg', event2: '超逆上' },
  'e9-SSR-hakuou':            { name: '白凰',              rarity: 'SSR', oura: '白', type: 'ライバル',   mon: null,   ext: 'jpg' },
  'e6l-SSR-arukadiasu':       { name: 'アルカディアス',    rarity: 'SSR', oura: '白', type: '丈夫さ',     mon: '無機', ext: 'jpg', terrain: '火山' },
  'a25i-MR-borusyakku':       { name: 'ボルシャック',      rarity: 'MR',  oura: '赤', type: 'バイタル',   mon: '魔族', ext: 'jpg', terrain: '火山' },
  'c23i-MR-naiara':           { name: 'ナイアーラ',        rarity: 'MR',  oura: '黄', type: 'フォーカス', mon: '魔族', ext: 'jpg', terrain: '雪山' },
  'c7-SSR-piisii':            { name: 'ピーシィ(黄)',      rarity: 'SSR', oura: '黄', type: '友人',       mon: null,   ext: 'jpg' },
  'c11j-MR-mirukii':          { name: 'ミルキィ',          rarity: 'MR',  oura: '黄', type: 'タフネス',   mon: '獣',   ext: 'jpg', event2: '超根性' },
  'd22g-MR-emuroudo':         { name: 'エムロード',        rarity: 'MR',  oura: '緑', type: 'ルミナス',   mon: '創造', ext: 'jpg', terrain: '森林' },
  'e3h-SSR-marijji':          { name: 'マリッジ',          rarity: 'SSR', oura: '白', type: 'かしこさ',   mon: '幻霊', ext: 'jpg', dist: '遠距離' },
  'd12g-MR-doruche':          { name: 'ドルチェ',          rarity: 'MR',  oura: '緑', type: 'アサルト',   mon: '創造', ext: 'jpg', event2: '超逆上' },
  'a3g-SSR-hao':              { name: 'ハオ',              rarity: 'SSR', oura: '赤', type: 'かしこさ',   mon: '創造', ext: 'jpg', terrain: '火山' },
  'a7-SSR-anna':              { name: '恐山アンナ',        rarity: 'SSR', oura: '赤', type: '友人',       mon: null,   ext: 'jpg' },
  'd13i-MR-asakurayou':       { name: '麻倉葉',            rarity: 'MR',  oura: '緑', type: 'テクニック', mon: '魔族', ext: 'jpg', dist: '中距離' },
  'e2j-SSR-rekusu':           { name: 'レクス',            rarity: 'SSR', oura: '白', type: 'ちから',     mon: '獣',   ext: 'jpg', terrain: '海岸' },
  'e18l-MR-rippii':           { name: 'リッピー',          rarity: 'MR',  oura: '白', type: 'フォース',   mon: '無機', ext: 'jpg', event2: '超必死' },
  'f9-SSR-hori':              { name: 'ホリィ',            rarity: 'SSR', oura: '黒', type: 'ライバル',   mon: null,   ext: 'jpg' },
  'f16h-MR-iburiisu':         { name: 'イブリース',        rarity: 'MR',  oura: '黒', type: 'インパクト', mon: '幻霊', ext: 'jpg', dist: '遠距離' },
  'f6l-SSR-araibu':           { name: 'アライブ',          rarity: 'SSR', oura: '黒', type: '丈夫さ',     mon: '無機', ext: 'jpg', dist: '近距離' },
  'f1g-SSR-tyakooru':         { name: 'チャコール',        rarity: 'SSR', oura: '黒', type: 'ライフ',     mon: '創造', ext: 'jpg', dist: '中距離' },
  'c19k-MR-ofurii':           { name: 'オフリィ',          rarity: 'MR',  oura: '黄', type: 'ジャッジ',   mon: '怪物', ext: 'jpg', event2: '超余裕' },
  'f21l-MR-serene':           { name: 'セレネ',            rarity: 'MR',  oura: '黒', type: 'クイック',   mon: '無機', ext: 'jpg', terrain: '砂漠' },
  'd6g-SSR-king':             { name: 'キング',            rarity: 'SSR', oura: '緑', type: '丈夫さ',     mon: '創造', ext: 'jpg', dist: '遠距離' },
  'a9-SSR-ban':               { name: 'バン',              rarity: 'SSR', oura: '赤', type: 'ライバル',   mon: null,   ext: 'jpg' },
  'c2h-SSR-meriodasu':        { name: 'メリオダス',        rarity: 'SSR', oura: '黄', type: 'ちから',     mon: '幻霊', ext: 'jpg', terrain: '雪山' },
  'b2l-SSR-rikanto':          { name: 'リカント',          rarity: 'SSR', oura: '青', type: 'ちから',     mon: '無機', ext: 'jpg', terrain: '森林' },
  'b9-SSR-siena':             { name: 'シエナ',            rarity: 'SSR', oura: '青', type: 'ライバル',   mon: null,   ext: 'jpg' },
  'b17h-MR-ryuujin':          { name: 'リュージン',        rarity: 'MR',  oura: '青', type: 'ガード',     mon: '幻霊', ext: 'jpg', event2: '超余裕' },
  'a5g-SSR-roozuheddo':       { name: 'ローズヘッド',      rarity: 'SSR', oura: '赤', type: '回避',       mon: '創造', ext: 'jpg', terrain: ['海岸', '砂漠'] },
  'a1j-SSR-kurousu':          { name: 'クロース',          rarity: 'SSR', oura: '赤', type: 'ライフ',     mon: '獣',   ext: 'jpg', dist: '近距離' },
  'd19h-MR-parumaa':          { name: 'パルマー',          rarity: 'MR',  oura: '緑', type: 'ジャッジ',   mon: '幻霊', ext: 'jpg', event2: '超必死' },
  'd2l-SSR-mikasa':           { name: 'ミカサ',            rarity: 'SSR', oura: '緑', type: 'ちから',     mon: '無機', ext: 'jpg', terrain: '火山' },
  'd7-SSR-rivai':             { name: 'リヴァイ',          rarity: 'SSR', oura: '緑', type: '友人',       mon: null,   ext: 'jpg' },
  'c6k-SSR-jonson':           { name: 'ジョンソン',        rarity: 'SSR', oura: '黄', type: '丈夫さ',     mon: '怪物', ext: 'jpg', terrain: '砂漠' },
  'c18k-MR-risuton':          { name: 'リストン',          rarity: 'MR',  oura: '黄', type: 'フォース',   mon: '怪物', ext: 'png', event2: '超根性' },
  'c9-SSR-porutsu':           { name: 'ポルツ(ライバル)',  rarity: 'SSR', oura: '黄', type: 'ライバル',   mon: null,   ext: 'png' },
  'e1g-SSR-yunibaasu':        { name: 'ユニバース',        rarity: 'SSR', oura: '白', type: 'ライフ',     mon: '創造', ext: 'png', dist: '中距離' },
  'e17g-MR-kyatoru':          { name: 'キャトル',          rarity: 'MR',  oura: '白', type: 'ガード',     mon: '創造', ext: 'png', event2: '超根性' },
  'a3i-SSR-mirimu':           { name: 'ミリム',            rarity: 'SSR', oura: '赤', type: 'かしこさ',   mon: '魔族', ext: 'png', dist: '遠距離' },
  'b7-SSR-verudora':          { name: 'ヴェルドラ',        rarity: 'SSR', oura: '青', type: '友人',       mon: null,   ext: 'png' },
  'b1i-SSR-rimuru':           { name: 'リムル',            rarity: 'SSR', oura: '青', type: 'ライフ',     mon: '魔族', ext: 'png', terrain: '森林' },
  'a6j-SSR-akazonaenusi':     { name: 'アカゾナエヌシ',    rarity: 'SSR', oura: '赤', type: '丈夫さ',     mon: '獣',   ext: 'png', dist: '近距離' },
  'b17h-MR-ruri':             { name: 'ルリ',              rarity: 'MR',  oura: '青', type: 'ガード',     mon: '幻霊', ext: 'png', event2: '超必死' },
  'f15k-MR-tanatosu':         { name: 'タナトス',          rarity: 'MR',  oura: '黒', type: 'アキュメン', mon: '怪物', ext: 'png', event2: '超本気' },
  'a16h-MR-ramusuiito':       { name: 'ラムスイート',      rarity: 'MR',  oura: '赤', type: 'インパクト', mon: '幻霊', ext: 'png', event2: '超根性' },
  'c14k-MR-suzuka':           { name: 'スズカ',            rarity: 'MR',  oura: '黄', type: 'フィジカル', mon: '怪物', ext: 'png', dist: '零距離' },
  'a13i-MR-miriamu':          { name: 'ミリアム',          rarity: 'MR',  oura: '赤', type: 'テクニック', mon: '魔族', ext: 'png', event2: '超逆上' },
  'e12i-MR-raburesu':         { name: 'ラブレス',          rarity: 'MR',  oura: '白', type: 'アサルト',   mon: '魔族', ext: 'png', dist: '零距離' },
  'd11g-MR-ratatosuku':       { name: 'ラタトスク',        rarity: 'MR',  oura: '緑', type: 'タフネス',   mon: '創造', ext: 'png', terrain: '森林' },
  'f6g-SSR-momonandhamusuke': { name: 'モモン＆ハムスケ',  rarity: 'SSR', oura: '黒', type: '丈夫さ',     mon: '創造', ext: 'jpg', dist: '遠距離' },
  'f10h-MR-rucas':            { name: 'ルーカス',          rarity: 'MR',  oura: '黒', type: '師匠',       mon: '幻霊', ext: 'jpg' },
  'f5h-SSR-tyakkuru':         { name: 'チャックル',        rarity: 'SSR', oura: '黒', type: '回避',       mon: '幻霊', ext: 'jpg', terrain: '火山' },
};
